name: CI

on:
  push:
    branches:
      - main
      - release-*
  pull_request: {}
  workflow_dispatch: {}

env:
  GO_VERSION: '1.17'
  DOCKER_BUILDX_VERSION: 'v0.4.2'

jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: ${{ env.DOCKER_BUILDX_VERSION }}
          install: true
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch History
        run: git fetch --prune --unshallow

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      # NOTE(hasheddan): make build currently includes unit tests target as a
      # prerequisite.
      - name: Build Binaries
        run: make build

      - name: Publish Artifacts to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/**
